const SESSION_WINDOW_MINUTES = Number(process.env.SESSION_WINDOW_MINUTES || 20);
const DOWNLOAD_WINDOW_SECONDS = Number(process.env.DOWNLOAD_WINDOW_SECONDS || 120);
const QUEUE_RATE_LIMIT_PER_SECOND = Number(process.env.QUEUE_RATE_LIMIT_PER_SECOND || 5);
const TOKEN_SECRET = process.env.TOKEN_SECRET || "change-this-secret";

const APPWRITE_ENDPOINT = process.env.APPWRITE_ENDPOINT || "";
const APPWRITE_PROJECT_ID = process.env.APPWRITE_PROJECT_ID || "";
const APPWRITE_API_KEY = process.env.APPWRITE_API_KEY || "";
const APPWRITE_DATABASE_ID = process.env.APPWRITE_DATABASE_ID || "";
const APPWRITE_USERS_COLLECTION_ID = process.env.APPWRITE_USERS_COLLECTION_ID || "";
const APPWRITE_HALLTICKETS_COLLECTION_ID = process.env.APPWRITE_HALLTICKETS_COLLECTION_ID || "";

export {
  SESSION_WINDOW_MINUTES,
  DOWNLOAD_WINDOW_SECONDS,
  QUEUE_RATE_LIMIT_PER_SECOND,
  TOKEN_SECRET,
  APPWRITE_ENDPOINT,
  APPWRITE_PROJECT_ID,
  APPWRITE_API_KEY,
  APPWRITE_DATABASE_ID,
  APPWRITE_USERS_COLLECTION_ID,
  APPWRITE_HALLTICKETS_COLLECTION_ID,
};
